CREATE DATABASE MYSQL_DATABASE;
CREATE USER 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PWD';
GRANT ALL PRIVILEGES ON MYSQL_DATABASE.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PWD';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PWD';